version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker.Dockerfile
    restart: always
    ports:
      - "3000:8080"
    deploy:
      mode: replicated
      replicas: 1